### ISSUE TITLE
form to propose new collateral type and price feed

### ISSUE THREAD

**Issue by 0xpatrickdev** [DCFoundation/cosmos-proposal-builder#15]
> A user should be able to execute well known proposals, like addVault and startPSM, by entering relevant parameters in a form. Certain fields, like ibc/denom, could be referenced via cosmos/bank
>
> Ideally, the user should be able to select from among multiple versions of a proposal via a dropdown, and the app would pull from a well known or user provided git url.
> https://github.com/0xpatrickdev/agoric-gov-proposal-hub/issues/8#issue-1962577660

> The benefit of direct support for addVault and startPSM is clear.
> 
> The benefit of a more general mechanism is less clear.
> 
> The are active discussions for [DOT](https://community.agoric.com/t/dot-inter-protocol-vaults-collateral-onboarding-discussion/403) and [stkATOM](https://community.agoric.com/t/stkatom-inter-protocol-vaults-collateral-onboarding-discussion/517), in particular.
> 
> It's less clear clear when another startPSM proposal will come along.
> https://github.com/0xpatrickdev/agoric-gov-proposal-hub/issues/8#issuecomment-1783616413

Original: https://github.com/0xpatrickdev/agoric-gov-proposal-hub/issues/15

**Comment by dckc** [comment]
I see [#66 Signaling proposal for new collateral: stOSMO](https://bigdipper.live/agoric/proposals/66) is out for votes; if it gets much support, that suggests this issue should get some priority.

cc @sufyaankhan @otoole-brendan

**Comment by dckc** [comment]
seems like this could subsume #17 by adding some checkmarks to omit the price feed and call to `addCollateral()`, leaving just the `mintHolder` and vbank registration.
