### ISSUE TITLE
[🏆 Bounty] Support Community Spend proposal type

### ISSUE THREAD

**Issue by FredRadford** [DCFoundation/cosmos-proposal-builder#51]
### Task Description
Support Community Spend proposal type
Update the CosGov.org application to support the community spend proposal type by adding in a community fund amount to spend and the wallet that should receive the funds if the proposal passes.

### Acceptance Criteria
User can select the primary Proposal type of "Community Spend."  
The UI must display the text, amount and wallet fields. If the voters approve a proposal, the community fund must transfer the amount specified to the wallet specified.

### Bounty Amount
8-10 hours estimated development work
3,000 BLD

### Eligibility
Developer should be familiar with Agoric chain development as well as the CosGov.org front end code

### Submission Requirements
Developer should submit a pull request as needed and provide documentation on what the changes are and how the new UI works.
Testing should be done on Agoric testnets and successfully transfer Agoric community funds to the specified wallet.

### Submission Deadline
Bounty should be completed within 3 weeks of accepting the bounty.

### Additional Information
There are additional UI/UX bounties for CosGov.org including adding templates as well as additional chains.

**Comment by ManyRios** [comment]
Hey @FredRadford I can help with this task!

**Comment by FredRadford** [comment]
> Hey @FredRadford I can help with this task!
#51 is already assigned, but please submit your information at https://dcfoundation.io/project/26153/ and I'd be happy to chat with you about others.
