### ISSUE TITLE
install bundle: check vstorage bundles key

### ISSUE THREAD

**Issue by dckc** [DCFoundation/cosmos-proposal-builder#8]
After installing a bundle, there's a vstorage key that should get updated with the bundle hash.
Ideally, this tool should wait for that signal and confirm it.

_IOU pointers to `agoric publish` details._

cc @kriskowal

**Comment by kriskowal** [comment]
Here’s how it works in `agoric publish`, and should be portable to web: https://github.com/Agoric/agoric-sdk/blob/master/packages/agoric-cli/src/publish.js#L316-L328
